# Python Basics

In [2]:
#numbers integers and floats

In [3]:
1

1

In [4]:
1.0

1.0

In [5]:
1+1

2

In [6]:
1*3

3

In [7]:
1/3

0.3333333333333333

In [9]:
2**4

16

In [13]:
3*4+1/9*2-1 #follows BODMAS--> brackets,brackets, exponents,division,multiplication,additio and substraction
#so the first to hapen here is 9/2

11.222222222222221

In [18]:
12%5 # mod -gives the remainder

2

# variable assignment

In [29]:
x=2
y=9
print(x)
print(y)

2
9


In [30]:
#or use
x,y=12,19
print(x)
print(y)

12
19


In [31]:
x+y

31

In [32]:
x=x+x
print(x)

24


In [33]:
#variable names should not start with numbers or special symbols like % or $ etc, or be a keyword

24

In [34]:
#Strings

In [35]:
'this is a string'

'this is a string'

In [36]:
"this is also a string"

'this is also a string'

In [37]:
#if you want a single qoute within a string use double quotes
"I can't fail. I have to succeed"

"I can't fail. I have to succeed"

In [51]:
name='Rakesh'
age=34
print('My name is {} and my age is {}'.format(name,age) ) # the {} will be replaced by the variables in the same order

#if you dont want to bother about the order above, then use this
print('my name is {one} and my age is {two}'.format(two=age,one=name))

My name is Rakesh and my age is 34
my name is Rakesh and my age is 34


In [55]:
x='python' #x is a sequence of elements and here each element is a letter
#accessing individual elements from a string can be done using INDEXING
#indexing starts from 0

In [67]:
print(x[0])
#accessing multiple elements is called slicing
#we can grab a slice using :
print(x[0:3])

p
pyt


In [75]:
print(x[0:])# grab everythg starting from index 0 untill the end
print(x[3:])# grab everythg starting from index 3 untill the end
print(x[3:5])# grab everythg starting from index 3 to ONE LESS THEN 5. i.e 4
print(x[:4])# grab everythg starting from begining untill index 3 ( NOT 4)

python
hon
ho
pyth


In [2]:
#boolean
1==1

True

In [5]:
True==1

True

In [6]:
int(False)

0

In [7]:
4>5

False

In [9]:
'abc'=='abcd'

False

In [10]:
'abc'=='ABC'

False

# Data Structures in python


# LISTS

In [77]:
#list---> a collection of numerics or strings or lists itself
# a list is always given by []

In [78]:
x=[1,2,3,"Python"]

In [79]:
x[2]="Nitish"
x

[1, 2, 'Nitish', 'Python']

In [80]:
#indexing in python
print (x[0])
print (x[-1])# prints the last element

1
Python


In [81]:
x[0:3]

[1, 2, 'Nitish']

In [29]:
#x[4]="R" will also give error. 
#use append functio to add elements to a list, not like this

In [6]:
x.append(["R"])

In [82]:
#a list can have lists within ie nested lists
#example
x.append(["Data","Science",4,5,6])

In [83]:
print(x)

[1, 2, 'Nitish', 'Python', ['Data', 'Science', 4, 5, 6]]


In [10]:
#Task 1--> get me "Science out of x above using indexing in python"

In [84]:
#insert elements at a particular position
x.insert(0,'A')
x

['A', 1, 2, 'Nitish', 'Python', ['Data', 'Science', 4, 5, 6]]

# Dictionaries in Python

In [85]:
y={"emp#1":"Raj",
  "emp#2":"Vijay",
  "emp#3":"Ramesh",
  "emp#4":"XY"}
print(y)

{'emp#1': 'Raj', 'emp#2': 'Vijay', 'emp#3': 'Ramesh', 'emp#4': 'XY'}


In [86]:
y[1]#dictionaries donot support indexing.i.e they are unordered

KeyError: 1

In [14]:
#When you create the dictionary, python doesn't care about in what
# order you wrote the elements and it won't remember the order after
# the object is created. You cannot expect it(regular dictionary) to 
#print in the same order. 

In [87]:
#Python dictionary is an unordered ( cannot be accessed by indexes) collection of items
#dictionaries are always given by {} and have key:value pair
y={"emp#1":"Raj",
  "emp#2":"Vijay",
  "emp#3":"Ramesh"}
my_dict = {'name': 'John', 1: [2, 4, 3]}

In [88]:
y.keys()

dict_keys(['emp#1', 'emp#2', 'emp#3'])

In [89]:
print (type(y.keys()))
print (y.values())

<class 'dict_keys'>
dict_values(['Raj', 'Vijay', 'Ramesh'])


In [90]:
print (y['emp#1']) # values can be accessed by their keys

Raj


In [91]:
#update a value by using its key
y['emp#2']="Suresh"

In [92]:
print (y)

{'emp#1': 'Raj', 'emp#2': 'Suresh', 'emp#3': 'Ramesh'}


In [24]:
del y        # delete entire dictionary

In [94]:
dict = {'Name': 'Zara', 'Age': 7, 'Name': 'Manni'} #duplicate keys

In [95]:
dict['Name']#the last value wins

'Manni'

In [96]:
y={"k1":"v1","k2":{1:[1,2,3]}}

In [97]:
y["k2"][1][0]="A"
print(y)

{'k1': 'v1', 'k2': {1: ['A', 2, 3]}}


In [29]:
dict = {['Name']: 'Zara', 'Age': 7} #Keys must be immutable.--which means they cannot
#be chnaged once assigned 
#Which means you can use strings, numbers 
#or tuples as dictionary keys but something like ['key'] is not allowed
#We can use arbitrary types as values in a dictionary, 
#but there is a restriction for the keys. 
#Only immutable data types can be used as keys, 
#i.e. no lists or dictionaries can be used as keys

TypeError: unhashable type: 'list'

In [98]:
temp={1:12,
     "k":[1,2,3],
     1:"newvalue"}
print(temp)
print(temp[1])

{1: 'newvalue', 'k': [1, 2, 3]}
newvalue


In [99]:
# add item in a dictonary
print (dict)
dict['address'] = 'Downtown'  

{'Name': 'Manni', 'Age': 7}


In [100]:
print (dict)

{'Name': 'Manni', 'Age': 7, 'address': 'Downtown'}


In [101]:
#DIFFERENCE BETWEEN LISTS AND DICTIONARIES
#Lists are ordered sets of objects, whereas dictionaries are unordered sets
#items in dictionaries are accessed via keys and not via their position

# TUPLES

In [42]:
#A tuple is a sequence of immutable Python objects. Tuples are sequences,
#just like lists. The differences between tuples and lists are, the tuples
#cannot be changed unlike lists and tuples use parentheses, whereas lists use square brackets.

In [43]:
type(x)

list

In [50]:
x=(1,2,3)

In [51]:
x[0]#this means tuples are ordered.i.e. they supoort indexing

1

In [52]:
x[0]=4 #this will give an error 
#tuples are immutable.i.e once assigned a value it cant be changed

TypeError: 'tuple' object does not support item assignment

In [53]:
tup1 = ('physics', 'chemistry', 1997, 2000)

In [54]:
tup1 = (50)
print (type(tup1)) #will give int
#so To write a tuple containing a single value you 
#have to include a comma, even though there is only one value
tup1 = (50,)
print (type(tup1))

<class 'int'>
<class 'tuple'>


In [94]:
#If you have data that doesn't change, implementing it as tuple will 
#guarantee that it remains write-protected.

# Set

In [ ]:
#A Set is an unordered collection data type that is iterable, immutable,
#and has no duplicate elements. Python’s set class represents the mathematical
#notion of a set. The major advantage of using a set, as opposed to a list,
#is that it has a highly optimized method for checking whether a 
#specific element is contained in the set.

In [2]:
x={1,2,3}
print (x)
x={1,1,1,2,3,4,5,6,7,4,3,2}
print (x)

{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7}


In [103]:
my_set = {1.0, "Hello", (1, 2, 3),(1.0,2.0)}
print (my_set)

{(1.0, 2.0), 1.0, 'Hello', (1, 2, 3)}


In [104]:
my_set = set([1,2,3,2])# we can make set from a list
print(my_set)

{1, 2, 3}


In [105]:
my_set[0]

TypeError: 'set' object does not support indexing

In [106]:
my_set[0]=2 #set does not support indexing, so error

TypeError: 'set' object does not support item assignment

In [107]:
x={1,2,3,(2,3,4)}
print(x)

{1, 2, 3, (2, 3, 4)}


# LOOPS IN PYTHON

In [10]:
x=[1,2,3]
#for loop in python
for i in x:
    print (i)
print(i)

1
2
3
3


In [108]:
#while loop in python
i=5
while i<10:
    print (i)#inside first loop
    if(i<8):
        print (i)#inside second loop
    i=i+1

5
5
6
6
7
7
8
9


In [109]:
#if elif else
if i<4:
    print ("i is less than 4")
elif i>4:
    print ("i is more than 4")
else:
    print ("i is equal to 4")

i is more than 4


In [76]:
# Prints out the numbers 0,1,2,3,4
for x in range(5):
    print(x)

0
1
2
3
4


In [77]:
# Prints out 3,5,7
for x in range(3, 8, 2):
    print(x)

3
5
7


In [79]:
#"break" and "continue" statements
# Prints out 0,1,2,3,4
#break will come out of all loops
count = 0
while True:
    print(count)
    count += 1
    if count >= 5:
        break       
print ("******")
# Prints out only odd numbers - 1,3,5,7,9
# continue comes out of the current loop
for x in range(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print(x)

0
1
2
3
4
******
1
3
5
7
9


# array

In [1]:
#NumPy array, formally called ndarray 
#elements are of the same type. if different it converts to the most complex type
import numpy as np

In [4]:
x=[1,2,3]
x_a=np.array(x)
type(x_a)

numpy.ndarray

In [5]:
x_a

array([1, 2, 3])

In [6]:
x=['A',1,2,3]
x_a=np.array(x)
print (x_a)

['A' '1' '2' '3']


In [7]:
x=np.array(range(20))

In [8]:
print (x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
x[2,1]#this doesnot work

IndexError: too many indices for array

In [10]:
x[[2,1]] # to print multiple elements with their index positions

array([2, 1])

In [11]:
y=x.reshape(2,10)
#y1=x.reshape(5,7) gives an error--total size of new array must be unchanged

In [12]:
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [13]:
y[:,(2,1)] # gives all rows and 3rd and 2nd Column

array([[ 2,  1],
       [12, 11]])

In [14]:
y[:,[2,1]]

array([[ 2,  1],
       [12, 11]])

In [15]:
y[:,range(4)]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [16]:
y[:,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [17]:
print (y)
print("\n")
print (y>5)
print (y[y>5])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


[[False False False False False False  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
print (y[0,[1,3]])
#accessing individual elements of an array
#syntax is --->  name_of_array[ row#, column#]
print (y[0,0])
print (y[0,1])
print (y[1,4])
#print y[2,1] #this gives an error
print (y[1,3:])

print ([y[0,i] for i in [0,3,4,5,7]])# to print randomly

[1 3]
0
1
14
[13 14 15 16 17 18 19]
[0, 3, 4, 5, 7]


In [172]:
y.max()

19

In [19]:
print (y[y>5]) #gives all elements which satisfy the condition
print (y[y>5].shape) # its shape is made 1D & output is a array
print ("*****")
print (type(y[y>5]))
print ("*****")
print (y>5)
print (type(y>5))
print ("*****")
print ([y>5])
print (type([y>5]))

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(14,)
*****
<class 'numpy.ndarray'>
*****
[[False False False False False False  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]
<class 'numpy.ndarray'>
*****
[array([[False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])]
<class 'list'>


In [20]:
y.shape # gives the number of rows and columns

(2, 10)

In [21]:
np.random.rand(10) #gives 10 random numbers between 0 & 1 from a uniform dist

array([0.4528625 , 0.94893079, 0.9733687 , 0.94328236, 0.18845079,
       0.0102623 , 0.13541511, 0.10347645, 0.7512357 , 0.51850164])

In [22]:
#gives 10 numbers from a normal dist wth mean 0 and sd=1
np.random.randn(10) 

array([-0.63519739,  0.4844892 ,  1.76738876,  1.64182418, -0.50637259,
        0.47441469,  0.19605362, -0.57176417, -0.47158684, -1.64899967])

In [23]:
#linspace(start, stop, N)# N evenly spaced points between start & Stop
x=np.linspace(1,20,6)
print (x)

[ 1.   4.8  8.6 12.4 16.2 20. ]


In [24]:
x=([1,2,3])# if its a list, it repeats 2 times
print (type(x))
print (x*2)
#if its an array it mutiplies
x=np.array([1,2,3])
print (x*2)

<class 'list'>
[1, 2, 3, 1, 2, 3]
[2 4 6]


In [25]:
a=[1,2,3]
b=[3,4,5]
print (a+b) #if a and b are lists
print (np.array(a)+np.array(b))#if a and b are arrays [They must be of same length]

[1, 2, 3, 3, 4, 5]
[4 6 8]


In [26]:
x=np.array(a)
y=np.array(b)
x[1:]-y[:-1] #break it into individual pieces to understand

array([-1, -1])

In [27]:
#forming a 2D array
x=np.array([[1,2,3],[5,6,7]])
print (x)
print (x.shape)

[[1 2 3]
 [5 6 7]]
(2, 3)


In [49]:
#find max/min/mean of an array
print(np.max(x))
print(np.min(x))
#using axis parameter we can get ma/min wrt row/columns
print(np.max(x,axis=0))#gives max of each row
print(np.max(x,axis=1))#gives max of each column

7
1
[5 6 7]
[3 7]


In [231]:
#difference between numpy arrays and lists
#1) same datatype vs multiple datatypes
#2) numpy arrays support vectorised operations. eg, multiple each element by a
# constant etc. lists cannnot do that

# Series

In [56]:
import pandas as pd

In [57]:
#series
#One-dimensional array with axis labels
label=["A","B","C"]
temp=[10,20,30]

In [58]:
arr=np.array(temp)
print(type(label))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [59]:
aseries=pd.Series(data=temp,index=label)

In [60]:
print(aseries)

A    10
B    20
C    30
dtype: int64


# DataFrame

In [61]:
df=pd.DataFrame(data=arr,index=label,columns=['column_one'])

In [62]:
df

column_one
A          10
B          20
C          30

In [63]:
#to access columns in a dataframe--> dataframe_name['columnName']
df['column_one'] #output is of type series
#OR
df.column_one

A    10
B    20
C    30
Name: column_one, dtype: int32

In [64]:
type(df['column_one'])

pandas.core.series.Series

In [65]:
#np.array([1,2,3,4]).reshape(2,2)
pd.DataFrame(data=np.array([1,2,3,4]).reshape(2,2),columns=['A','B'])

A  B
0  1  2
1  3  4

In [66]:
#Features of DataFrame
#each column is an Series
#columns can be of different data type
#dataframes are like excel spreadsheet or SQL tables

In [67]:
#if no row index or column name is given, it takes 0,1,2,3,.. by default

In [68]:
df = pd.DataFrame() #empty dataframe
print (df)

Empty DataFrame
Columns: []
Index: []


In [130]:
##creating dataframe from LISTS
import pandas as pd
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data,dtype=float)
print (df)

    Name   Age
0    Tom  28.0
1   Jack  34.0
2  Steve  29.0
3  Ricky  42.0


In [31]:
import pandas as pd
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])#to give our 
#own index to the rows
print (df)

        Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42


In [132]:
#del a column
#del df['columnName']
#or
#df.drop(['columnName'],axis=1,inplace=True)
#inplace=True is used to overwrite

In [133]:
df.drop(['Age'],axis=1)#without inplace=True it just prints the result

Name
rank1    Tom
rank2   Jack
rank3  Steve
rank4  Ricky

In [70]:
from numpy.random import randn
import numpy as np
df = pd.DataFrame(np.random.rand(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
print (df)

          W         X         Y         Z
A  0.551058  0.642311  0.154769  0.929872
B  0.156971  0.855227  0.754905  0.384830
C  0.502540  0.358849  0.975235  0.834152
D  0.865794  0.850530  0.770665  0.526100
E  0.704567  0.690940  0.856706  0.887362


# Selection and Indexing

In [33]:
#to access multiple columns
# Pass a list of column names
df[['W','Z']]

W         Z
A  0.940005  0.479319
B  0.945138  0.862078
C  0.214414  0.761927
D  0.155803  0.005407
E  0.549006  0.540871

In [35]:
type(df['W'])#DataFrame Columns are just Series

pandas.core.series.Series

In [36]:
df['new'] = df['W'] + df['Y'] #creating a new columns
print (df)

          W         X         Y         Z       new
A  0.940005  0.734051  0.043959  0.479319  0.983964
B  0.945138  0.323157  0.357556  0.862078  1.302694
C  0.214414  0.253099  0.950299  0.761927  1.164713
D  0.155803  0.178187  0.213568  0.005407  0.369372
E  0.549006  0.383872  0.587168  0.540871  1.136174


In [37]:
df.drop('new',axis=1,inplace=True)
print (df)

          W         X         Y         Z
A  0.940005  0.734051  0.043959  0.479319
B  0.945138  0.323157  0.357556  0.862078
C  0.214414  0.253099  0.950299  0.761927
D  0.155803  0.178187  0.213568  0.005407
E  0.549006  0.383872  0.587168  0.540871


In [42]:
print(df.loc['A','X']) #loc is used when you call row/col by its name

0.734050634845165


In [43]:
print(df.loc['A',['X','W']])

X    0.734051
W    0.940005
Name: A, dtype: float64


In [45]:
print(df.loc[['A','B'],['X','W']])

          X         W
A  0.734051  0.940005
B  0.323157  0.945138


In [75]:
df

W         X         Y         Z
A  0.551058  0.642311  0.154769  0.929872
B  0.156971  0.855227  0.754905  0.384830
C  0.502540  0.358849  0.975235  0.834152
D  0.865794  0.850530  0.770665  0.526100
E  0.704567  0.690940  0.856706  0.887362

In [46]:
#selecting rows
print (df.loc['A'])  #use loc if yu want to access by row or column label
print (df.iloc[2])  #use iloc if yu want to access by row index

W    0.940005
X    0.734051
Y    0.043959
Z    0.479319
Name: A, dtype: float64
W    0.214414
X    0.253099
Y    0.950299
Z    0.761927
Name: C, dtype: float64


In [47]:
df

W         X         Y         Z
A  0.940005  0.734051  0.043959  0.479319
B  0.945138  0.323157  0.357556  0.862078
C  0.214414  0.253099  0.950299  0.761927
D  0.155803  0.178187  0.213568  0.005407
E  0.549006  0.383872  0.587168  0.540871

In [51]:
print(df.iloc[2,:])

W    0.214414
X    0.253099
Y    0.950299
Z    0.761927
Name: C, dtype: float64


In [52]:
print(df.iloc[:,:])

          W         X         Y         Z
A  0.940005  0.734051  0.043959  0.479319
B  0.945138  0.323157  0.357556  0.862078
C  0.214414  0.253099  0.950299  0.761927
D  0.155803  0.178187  0.213568  0.005407
E  0.549006  0.383872  0.587168  0.540871


In [54]:
print(df.iloc[:,:2])

          W         X
A  0.940005  0.734051
B  0.945138  0.323157
C  0.214414  0.253099
D  0.155803  0.178187
E  0.549006  0.383872


In [55]:
print(df.iloc[:,1:4])

          X         Y         Z
A  0.734051  0.043959  0.479319
B  0.323157  0.357556  0.862078
C  0.253099  0.950299  0.761927
D  0.178187  0.213568  0.005407
E  0.383872  0.587168  0.540871


In [62]:
df[df>0]

W         X         Y         Z
A  0.631426  0.841246  0.040519  0.124301
B  0.443945  0.692897  0.595954  0.524745
C  0.678816  0.307960  0.092722  0.700019
D  0.563085  0.864303  0.984596  0.544833
E  0.037025  0.088205  0.654060  0.748625

In [71]:
df[df['W']>0.5][['X','Z']]

X         Z
A  0.841246  0.124301
C  0.307960  0.700019
D  0.864303  0.544833

In [64]:
df[df['W']>0]["W"]

A    0.631426
B    0.443945
C    0.678816
D    0.563085
E    0.037025
Name: W, dtype: float64

In [86]:
#For two conditions you can use | and & with parenthesis
df[(df['W']>0) & (df['Y'] > 0.2)]

W         X         Y         Z
B  0.156971  0.855227  0.754905  0.384830
C  0.502540  0.358849  0.975235  0.834152
D  0.865794  0.850530  0.770665  0.526100
E  0.704567  0.690940  0.856706  0.887362